Repository navikt/nav-dekoratoren, pull requests merged in 2020-07, with the labels that each got.

#512 Feedback-komponent: Versjon 1
  package-lock.json
  src/komponenter/footer/feedback/Feedback.less
  src/komponenter/footer/feedback/Feedback.tsx
  src/komponenter/footer/footer-regular/FooterRegular.tsx
  src/tekster/ledetekster.ts
  src/utils/amplitude.ts
  src/utils/hotjar-surveys.js
  src/utils/url-filter/url-filter.ts
  src/utils/url-filter/url-whitelist.json
Labels: design, enhancement

#516 Fiks visningsbug for Feedback-komponenten
  src/komponenter/footer/footer-regular/FooterRegular.tsx
  src/utils/url-filter/path-whitelist.json
  src/utils/url-filter/url-filter.ts
  src/utils/url-filter/url-whitelist.json
Labels: bug

#548 La til lenker i whitelisting
  src/utils/url-filter/path-whitelist.json
Labels: enhancement

#550 Aktiver komponenten på flere subdomener
  src/utils/url-filter/path-whitelist.json
Labels: enhancement
